vich_uploader:
    db_driver: orm

    mappings:
        review_images:
            uri_prefix: /images/review_images
            upload_destination: '%kernel.project_dir%/public/images/review_images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
