vich_uploader:
    db_driver: orm

    mappings:
        review_images:
            uri_prefix: /images/review_images
            upload_destination: '%kernel.project_dir%/public/images/review_images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        profile_photos:
            uri_prefix: /images/profile_photos
            upload_destination: '%kernel.project_dir%/public/images/profile_photos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        lessons_videos:
            uri_prefix: /videos/lessons_videos
            upload_destination: '%kernel.project_dir%/public/videos/lessons_videos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
